### ISSUE TITLE
Wrong spell/class associations in spell descriptions and spell lists

### ISSUE THREAD

**Issue by fl-nk** [oznogon/cc-srd5#4]
* Find Familiar spell entry: Described as a Warlock spell (remove), but it is a Wizard spell (add).

**Comment by fl-nk** [comment]
Eldritch Blast is listed as a 3rd level Sorcerer spell instead of as a Warlock cantrip. Both in the spell entry and in the spell lists.

**Comment by fl-nk** [comment]
- Poison Spray is missing from the list of Warlock cantrips.
- The Warlock class is missing in the list of classes that can cast Poison Spray in the Poison Spray entry.

**Comment by oznogon** [comment]
Thank you!
